let id = 0;

let shawarma = [
  {
    id: ++id,
    category: "ШАУРМА НА УГЛЯХ",
    img: "images/menu_item/shawarma/Курица.png",
    title: "ШАУРМА С КУРИЦЕЙ",
    price: "170",
    weight: "350г",
    count: 0,
  },
  {
    id: ++id,
    category: "ШАУРМА НА УГЛЯХ",
    img: "images/menu_item/shawarma/Свинина.png",
    title: "ШАУРМА СО СВИНИНОЙ",
    price: "220",
    weight: "350г",
    count: 0,
  },
  {
    id: ++id,
    category: "ШАУРМА НА УГЛЯХ",
    img: "images/menu_item/shawarma/Говядина.png",
    title: "ШАУРМА С ГОВЯДИНОЙ",
    price: "280",
    weight: "350г",
    count: 0,
  },
  {
    id: ++id,
    category: "ШАУРМА НА УГЛЯХ",
    img: "images/menu_item/shawarma/Баранина.png",
    title: "ШАУРМА С БАРАНИНОЙ",
    price: "300",
    weight: "350г",
    count: 0,
  },
];

let barbecue = [
  {
    id: ++id,
    category: "ШАШЛЫК",
    img: "images/menu_item/barbecue/Свиная шейка.png",
    title: "свиная шейка",
    price: "390",
    weight: "250г",
    count: 0,
  },
  {
    id: ++id,
    category: "ШАШЛЫК",
    img: "images/menu_item/barbecue/Свиные ребра.png",
    title: "Свиные ребра",
    price: "340",
    weight: "250г",
    count: 0,
  },
  {
    id: ++id,
    category: "ШАШЛЫК",
    img: "images/menu_item/barbecue/Филе телятины.png",
    title: "Филе телятины",
    price: "499",
    weight: "250г",
    count: 0,
  },
  {
    id: ++id,
    category: "ШАШЛЫК",
    img: "images/menu_item/barbecue/Корейка ягненка.png",
    title: "Корейка ягненка",
    price: "499",
    weight: "170г",
    count: 0,
  },
  {
    id: ++id,
    category: "ШАШЛЫК",
    img: "images/menu_item/barbecue/Мякоть баранина.png",
    title: "Мякоть Баранина",
    price: "499",
    weight: "250г",
    count: 0,
  },
  {
    id: ++id,
    category: "ШАШЛЫК",
    img: "images/menu_item/barbecue/Ребра баранины.png",
    title: "Ребра баранина",
    price: "440",
    weight: "250г",
    count: 0,
  },
  {
    id: ++id,
    category: "ШАШЛЫК",
    img: "images/menu_item/barbecue/Куриные крылья.png",
    title: "Куриные крылья",
    price: "250",
    weight: "250г",
    count: 0,
  },
  {
    id: ++id,
    category: "ШАШЛЫК",
    img: "images/menu_item/barbecue/Куриные бедра.png",
    title: "Кириное бедро",
    price: "290",
    weight: "230г",
    count: 0,
  },
  {
    id: ++id,
    category: "ШАШЛЫК",
    img: "images/menu_item/barbecue/Куриное филе.png",
    title: "Куриное филе",
    price: "320",
    weight: "250г",
    count: 0,
  },
  {
    id: ++id,
    category: "ШАШЛЫК",
    img: "images/menu_item/barbecue/Крылья барбекю.png",
    title: "Крылья барбекю",
    price: "280",
    weight: "280г",
    count: 0,
  },
];

let drinks = [
  {
    id: ++id,
    category: "НАПИТКИ",
    img: "images/menu_item/drinks/добрый яблоко.jpg",
    title: "добрый яблоко",
    price: "60",
    weight: "0,2",
    count: 0,
  },
  {
    id: ++id,
    category: "НАПИТКИ",
    img: "images/menu_item/drinks/Дюшес.jpg",
    title: "Дюшес",
    price: "100",
    weight: "0,5",
    count: 0,
  },
  {
    id: ++id,
    category: "НАПИТКИ",
    img: "images/menu_item/drinks/кола.jpg",
    title: "кола",
    price: "90",
    weight: "0,33",
    count: 0,
  },
  {
    id: ++id,
    category: "НАПИТКИ",
    img: "images/menu_item/drinks/пепси0,3.jpg",
    title: "пепси 0,33",
    price: "80",
    weight: "0,33",
    count: 0,
  },
  {
    id: ++id,
    category: "НАПИТКИ",
    img: "images/menu_item/drinks/пепси0,5.jpg",
    title: "пепси 0,5",
    price: "90",
    weight: "0,5",
    count: 0,
  },
  {
    id: ++id,
    category: "НАПИТКИ",
    img: "images/menu_item/drinks/святой источник.jpg",
    title: "Святой источник",
    price: "60",
    weight: "0,5",
    count: 0,
  },
  {
    id: ++id,
    category: "НАПИТКИ",
    img: "images/menu_item/drinks/сенежская с газом.jpg",
    title: "Сенежская с газом",
    price: "60",
    weight: "0,5",
    count: 0,
  },
  {
    id: ++id,
    category: "НАПИТКИ",
    img: "images/menu_item/drinks/тан.jpg",
    title: "тан",
    price: "150",
    weight: "0,5",
    count: 0,
  },
];

let fish = [
  {
    id: ++id,
    category: "РЫБА НА МАНГАЛЕ",
    img: "images/menu_item/fish/Дорадо.png",
    title: "Дорадо",
    price: "699",
    weight: "250г",
    count: 0,
  },
  {
    id: ++id,
    category: "РЫБА НА МАНГАЛЕ",
    img: "images/menu_item/fish/Сибас.png",
    title: "Сибас",
    price: "699",
    weight: "250г",
    count: 0,
  },
  {
    id: ++id,
    category: "РЫБА НА МАНГАЛЕ",
    img: "images/menu_item/fish/Стейк семги.png",
    title: "Стейк семги",
    price: "799",
    weight: "250г",
    count: 0,
  },
  {
    id: ++id,
    category: "РЫБА НА МАНГАЛЕ",
    img: "images/menu_item/fish/Форель.png",
    title: "Форель",
    price: "699",
    weight: "250г",
    count: 0,
  },
];

let garnish = [
  {
    id: ++id,
    category: "ГАРНИР",
    img: "images/menu_item/garnish/Грибы.png",
    title: "Грибы",
    price: "190",
    weight: "80г",
    count: 0,
  },
  {
    id: ++id,
    category: "ГАРНИР",
    img: "images/menu_item/garnish/Картошка на углях.png",
    title: "Картошка на углях",
    price: "100",
    weight: "100г",
    count: 0,
  },
  {
    id: ++id,
    category: "ГАРНИР",
    img: "images/menu_item/garnish/Картошка с курдюком.png",
    title: "Картошка с курдюком",
    price: "140",
    weight: "100г",
    count: 0,
  },
  {
    id: ++id,
    category: "ГАРНИР",
    img: "images/menu_item/garnish/Картошка с салом.png",
    title: "Картошка с салом",
    price: "120",
    weight: "100г",
    count: 0,
  },
  {
    id: ++id,
    category: "ГАРНИР",
    img: "images/menu_item/garnish/Овощи на мангале.png",
    title: "Овощи на мангале",
    price: "290",
    weight: "300г",
    count: 0,
  },
  {
    id: ++id,
    category: "ГАРНИР",
    img: "images/menu_item/garnish/Свежие овощи.png",
    title: "Свежие овощи",
    price: "250",
    weight: "230г",
    count: 0,
  },
  {
    id: ++id,
    category: "ГАРНИР",
    img: "images/menu_item/garnish/Хоровац.png",
    title: "Хоровац",
    price: "300",
    weight: "300г",
    count: 0,
  },
];

let lula_kebab = [
  {
    id: ++id,
    category: "ЛЮЛЯ - КЕБАБ",
    img: "images/menu_item/lula_kebab/Баранина.png",
    title: "Баранина",
    price: "290",
    weight: "170г",
    count: 0,
  },
  {
    id: ++id,
    category: "ЛЮЛЯ - КЕБАБ",
    img: "images/menu_item/lula_kebab/Говядина.png",
    title: "Говядина",
    price: "270",
    weight: "170г",
    count: 0,
  },
  {
    id: ++id,
    category: "ЛЮЛЯ - КЕБАБ",
    img: "images/menu_item/lula_kebab/Из курицы.png",
    title: "Из курицы",
    price: "240",
    weight: "170г",
    count: 0,
  },
  {
    id: ++id,
    category: "ЛЮЛЯ - КЕБАБ",
    img: "images/menu_item/lula_kebab/Свинина.png",
    title: "Свинина",
    price: "260",
    weight: "170г",
    count: 0,
  },
];

let sauce = [
  {
    id: ++id,
    category: "СОУСЫ",
    img: "images/menu_item/sauce/томатный.png",
    title: "томатный",
    price: "50",
    weight: "50мл",
    count: 0,
  },
  {
    id: ++id,
    category: "СОУСЫ",
    img: "images/menu_item/sauce/чесночный.png",
    title: "чесночный",
    price: "50",
    weight: "50мл",
    count: 0,
  },
];

let bakery = [
  {
    id: ++id,
    category: "ВЫПЕЧКА",
    img: "images/menu_item/bakery/лаваш.png",
    title: "лаваш",
    price: "40",
    weight: "75г",
    count: 0,
  },
];

let mass = [
  ...shawarma,
  ...barbecue,
  ...drinks,
  ...fish,
  ...garnish,
  ...lula_kebab,
  ...sauce,
  ...bakery,
];

export default mass;
